spring:
  application:
    name: user-service
  mvc:
    servlet:
      path: /user-service

server:
  port: 8088

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

security:
  jwt:
    token:
      key: ENC(LW2nGQYI2HLpEfTfMWmP5wGOp1/BuNxk)
