spring:
  application:
    name: email-service
  mvc:
    servlet:
      path: /email-service
    pathmatch:
      matching-strategy: ant_path_matcher
  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(qCI2qKyrKYaZymWTxQerjGwuFpPGlw8cQDfKhdLqet0=)
    password: ENC(bzh6mpJfO2dCaoGKLiOAa4FMWZnSAqF5PrGFvCOWKEY=)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

database:
  hibernate:
    url: jdbc:mysql://database-2.cickoqfkvdpa.us-east-2.rds.amazonaws.com:3306/authentication?userSSL=false
    driver: com.mysql.cj.jdbc.Driver
    username: admin
    password: ENC(1ba+Hk/BS0QnEnu/DID0QZMOzVZbDSdL)
    dialect: org.hibernate.dialect.MySQLDialect
    showsql: true

server:
  port: 8085

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

security:
  jwt:
    token:
      key: ENC(LW2nGQYI2HLpEfTfMWmP5wGOp1/BuNxk)
